version: '3.8'

services:
  pgadmin:
    image: dpage/pgadmin4
    restart: always
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@admin.com   # Cambiá este mail
      PGADMIN_DEFAULT_PASSWORD: admin          # Cambiá este password
    ports:
      - "5050:80"
    depends_on:
      - db
    volumes:
      - pgadmin_data:/var/lib/pgadmin

volumes:
  pgadmin_data:
